;;;; listicles.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'listicles
  'listicles
  (scheme#list)
  '((nth . listicles#nth)
    (range . listicles#range)
    (split-by . listicles#split-by)
    (sublist . listicles#sublist)
    (list-includes . listicles#list-includes))
  (scheme#list)
  (scheme#list))

;; END OF FILE
